### ISSUE TITLE
sqlite3.OperationalError: no such table: terms_to_entries

### ISSUE THREAD

**Issue by er1chsu** [ra1nb0rn/cpe_search#6]
hi 
im running Python 3.8.9 .
 is there any fix to this error? 

```
python cpe_search.py -q "Sduo 1.8.2"

Traceback (most recent call last):
  File "cpe_search.py", line 1097, in <module>
    results[query] = search_cpes(query, args.number, -1, config).get('cpes', [])
  File "cpe_search.py", line 991, in search_cpes
    cpes = _search_cpes([query], count=count, threshold=CPE_SEARCH_THRESHOLD_ALT, config=config)
  File "cpe_search.py", line 660, in _search_cpes
    db_cursor.execute(db_query, (word, ))
sqlite3.OperationalError: no such table: terms_to_entries
```

**Comment by ra1nb0rn** [comment]
Hi, cpe_search changed its database format some time ago. I think that's the reason for your error.

I think performing an update of the local database with ``-u`` should fix the error. Alternatively, you can also download a prebuilt version from my other repository [search_vulns](https://github.com/ra1nb0rn/search_vulns/): https://github.com/ra1nb0rn/search_vulns/releases/latest/download/cpe-search-dictionary.db3

Let me know if this fixed your issue or if you need any more help.

PS: I think you're looking for `Sudo` and not `Sduo` ;)

**Comment by er1chsu** [comment]
yes, `Sduo`  is my typo, thanks.

after downlaod [cpe-search-dictionary.db3](https://github.com/ra1nb0rn/search_vulns/releases/download/v0.5.0/cpe-search-dictionary.db3) 

I can run like this 
```
python cpe_search.py -q "Sudo 1.8.2"
cpe:2.3:a:sudo_project:sudo:1.8.2:*:*:*:*:*:*:*
[('cpe:2.3:a:sudo_project:sudo:1.8.2:*:*:*:*:*:*:*', 0.8812565009687703),
 ('cpe:2.3:a:sudo_project:sudo:1.8.2:*:*:*:*:*:*:*', 0.674613486972654),
 ('cpe:2.3:a:sudo_project:sudo:1.6.8:p10:*:*:*:*:*:*', 0.6525629975748669)]
 ```
But updating DB still error 
```
python cpe_search.py -u
[+] Getting NVD's official CPE data (might take some time)
[-] No API Key found - Requests will be sent at a rate of 5 per 30s. To lower build time, consider getting an NVD API Key.
[-] Failed updating the local CPE database!
```

**Comment by er1chsu** [comment]
after apply api key 

look good but still not update success

```
python cpe_search.py -uv -k ****** 
[+] Getting NVD's official CPE data (might take some time)
[+] API Key found - Requests will be sent at a rate of 25 per 30s.
Got the following exception when downloading CPE data via API: Cannot connect to host services.nvd.nist.gov:443 ssl:default [Connect call failed ('18.235.227.114', 443)]
Got the following exception when downloading CPE data via API: Cannot connect to host services.nvd.nist.gov:443 ssl:default [Connect call failed ('18.235.227.114', 443)]
Got the following exception when downloading CPE data via API: Cannot connect to host services.nvd.nist.gov:443 ssl:default [Connect call failed 
```

**Comment by ra1nb0rn** [comment]
I'm glad downloading the prebuilt database worked for you and solved the issue.

Regarding the failing update, I don't think there is much I can do. The underlying issue is that the tool cannot connect to the NVD's API on a network level. This is not directly related to the cpe_search, however. I've been experiencing similar problems from time to time, but can't reproduce it now. How I usually get around this problem is trying a couple of times (with an API key) or using a VPN / different network. What might also help is decreasing the rate limit here, even though it's already within the NVD's guidelines: https://github.com/ra1nb0rn/cpe_search/blob/master/cpe_search.py#L343

Otherwise, my tool [search_vulns](https://github.com/ra1nb0rn/search_vulns) rebuilds its CPE database weekly, so you can always download a recent version from https://github.com/ra1nb0rn/search_vulns/releases/latest/download/cpe-search-dictionary.db3 . I'm sorry I couldn't be of more help and hope my suggestions work for you. I don't really know how else to fix this problem, since I perceive it to be a fault of the NVD API.

Let me know if these suggestions work out for you or if you have any more insights / ideas or issues.

**Comment by ra1nb0rn** [comment]
Hi @er1chsu , since I haven't heard back from you, I'm closing this issue.

I'm sorry if I couldn't be of much help. As I've said though, I perceive this to be an issue with the NVD API.

I hope my suggested workarounds have helped you. If anything is still unclear or needs to be resolved, respond here and we'll reopen the issue.
